services:
  api:
    restart: always
    ports:
      - "8080:8080"
    build: .
    volumes:
      - ./:/app
    env_file: ".env"
    depends_on:
      - pg

  pg:
    image: postgres:16.4
    restart: always
    ports:
      - ${DATABASE_PORT}:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_NAME=${DATABASE_NAME}
